name: 'Main Branch'
on: [push, workflow_dispatch]

jobs:
  golang-test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18.1'
      - name: Run tests
        run: |-
          cd cmd/test
          go test
