name: 'Main Branch'
on: [push, workflow_dispatch]

jobs:
  golang-test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install golang
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18.1'
      - name: Run tests
        run: |-
          cd cmd/test
          go test
  newman-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install newman
        run: npm install -g newman
      - name: Run newman tests
        run: |-
          go run cmd/* &
          sleep 5
          cd test/newman
          newman run perlance.postman_collection.json -n 10